### ISSUE TITLE
Temporal Eraser crashes server

### ISSUE THREAD

**Issue by NovaAstral** [SpectrumFATM/MoreVortexManipulators#1]
As the title says, the Temporal Eraser crashes the server when its used. It seems to be related to the never ending lightning storm it spawns. Sadly I do not have logs as I am not the owner of the server, I am just a player.

**Comment by SpectrumFATM** [comment]
Hiya, this is most likely due to the server resources available not the mod. I run this on a server with no issue, unless I can be given a crash log then there's not much I can do about this.
